<div class="row">
    <div class="col-md-12 text-center">
        <h1>Classements "<?= $type_ranking ?>" de l'épreuve</h1>
        <h4><?= $event->getName()?>, le <?=$event->getDateEvent()->format('d/m/Y à H:i:s');?></h4>
    </div>
</div>

<div class="table-responsive mt-20">
    <table class="table">
        <thead>
            <tr>
                <td>position</td>
                <td>N° dossard</td>
                <td>Nom</td>
                <td>Prénom</td>
                <td>Chrono</td>
            </tr>
        </thead>
        <tbody>
            <?php if($this->participants){ ?>
                <?php                
                foreach($this->participants as $key => $participant){ ?>
                    <tr>
                        <td><?= $key + 1 ?>°</td>
                        <td># <?=$participant->getBibNumber()?></td>
                        <td><?=$participant->getLastname()?></td>
                        <td><?=$participant->getFirstname()?></td>
                        <td><?= $participant->getRunningTime() ?></td>
                    </tr>
                <?php } ?>
            <?php } ?>

        </tbody>
    </table>
</div>
</div>
</div>