<div class="row">
    <div class="col-md-12 text-center">
        <h1>Formulaire participant</h1>
    </div>
</div>

<div class="row mt-20">
    <div class="col-md-12">
        <?php
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <?=$this->formElement($form->get('id'))?>
        <div class="form-group">
            <label class="col-sm-2 control-label"><?=$this->formLabel($form->get('firstname'))?></label>
            <div class="col-sm-10">
                <?=$this->formElement($form->get('firstname'))?>
                <?=$this->formElementErrors($form->get('firstname'))?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label"><?=$this->formLabel($form->get('lastname'))?></label>
            <div class="col-sm-10">
                <?=$this->formElement($form->get('lastname'))?>
                <?=$this->formElementErrors($form->get('lastname'))?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label"><?=$this->formLabel($form->get('sex'))?></label>
            <div class="col-sm-10">
                <div class="radio">
                    <?=$this->formElement($form->get('sex'))?>
                    <?=$this->formElementErrors($form->get('sex'))?>
                </div>
            </div>
        </div>
        <?php if (null !== $form->get('bibNumber')->getValue()) : ?>
        <div class="form-group">
            <label class="col-sm-2 control-label"><?=$this->formLabel($form->get('time'))?></label>
            <div class="col-sm-10">
                <?=$this->formElement($form->get('time'))?>
                <?=$this->formElementErrors($form->get('time'))?>
                <span>avec le dossard n° <?= $form->get('bibNumber')->getValue() ?> (donc on ne peut plus changer d'évènement)</span>
            </div>
        </div>
        <?php else : ?>
        <div class="form-group">
            <label class="col-sm-2 control-label"><?=$this->formLabel($form->get('event'))?></label>
            <div class="col-sm-10">
                <?=$this->formElement($form->get('event'))?>
                <?=$this->formElementErrors($form->get('event'))?>
            </div>
        </div>
        <div>Le dossard n'a pas encore été attribué.</div>
        </br>
        <?php endif; ?>
        <div class="alert alert-warning" role="alert">Si les autres numéros de dossards ont déjà été attribué, il faudra relancer la génération des dossards pour mettre à jour les participants sans dossard.</div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <?=$this->formSubmit($form->get('submit'));?>
            </div>
        </div>
        <?=$this->form()->closeTag();?>
    </div>
</div>